on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  # pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: github-pages
        continue-on-error: true
      - uses: actions/setup-node@v3
        with:
          node-version: node
      - uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
      - run: npx jest --coverage --coverageDirectory coverage/${{ github.head_ref || github.ref_name }}
      - run: ls -R ./coverage
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: coverage
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
