on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: read
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: github-pages
      - run: npx jest --coverage --coverageDirectory ${{ github.head_ref || github.ref_name }}
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: coverage
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
