on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  # pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      github_pages_dir: _site
      jest_coverage_dir: branches/${{ github.head_ref || github.ref_name }}/coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download-artifact
        with:
          name: github-pages
          path: ${{ env.github_pages_dir }}
        continue-on-error: true
      - run: mkdir -p ${{ env.github_pages_dir }}
      - run: ls -R .
      - uses: actions/setup-node@v3
        with:
          node-version: node
      - uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
      - run: npx jest --coverage --coverageDirectory ${{ env.github_pages_dir }}/${{ env.jest_coverage_dir }} --colors
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.github_pages_dir }}
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
