on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  # pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      coverage_report_dir: docs/branches/${{ github.head_ref || github.ref_name }}/coverage
    steps:
      - name: Checkout branch ${{ github.head_ref || github.ref_name }}
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: node
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm ci
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
      - name: Cache github pages
        uses: actions/cache@v3
        id: cache_github_pages
        with:
          path: docs
          key: github-pages
      - name: Run jest
        run: npx jest --colors --coverage --coverageDirectory .coverage
      - name: Remove coverage report if exists
        run: rm -rf ${{ env.coverage_report_dir }}
      - name: Create coverage report directory
        run: mkdir -p ${{ env.coverage_report_dir }}
      - name: Copy coverage report
        run: cp -RT .coverage/lcov-report ${{ env.coverage_report_dir }}
      - name: Upload github pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs
      - name: Configure github pages
        uses: actions/configure-pages@v3
      - name: Deploy github pages
        uses: actions/deploy-pages@v2
