on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusables/test.yml

  save-pages-cache:
    needs: [test]
    uses: ./.github/workflows/reusables/save-pages-cache.yml

  deploy-pages:
    needs: [save-pages-cache]
    uses: ./.github/workflows/reusables/deploy-pages.yml
