on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  # pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      github_pages_dir: github_pages
      coverage_report_dir: branches/${{ github.head_ref || github.ref_name }}/coverage
    steps:
      - name: Checkout branch ${{ github.head_ref || github.ref_name }}
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: node
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm ci
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
      - name: Cache coverage report
        uses: actions/cache@v3
        id: cache_github_pages
        with:
          path: ${{ env.github_pages_dir }}
          key: github-pages
      - name: Delete previous coverage report if exists
        run: rm -rf ${{ env.github_pages_dir }}/${{ env.coverage_report_dir }}
      - name: Run jest
        run: npx jest --colors --coverage --coverageDirectory ${{ env.github_pages_dir }}/${{ env.coverage_report_dir }}
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.github_pages_dir }}
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v2
