on:
  workflow_call:

env:
  branch_dir: docs/coverage/${{ github.head_ref || github.ref_name }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: node
      - uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
      - name: Run jest
        run: npx jest --colors --coverage --coverageDirectory .coverage
      - name: Prepare artifact
        run: |
          mkdir -p ${{ env.branch_dir }}
          cp -vRT .coverage/lcov-report ${{ env.branch_dir }}
      - uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: docs
